# Generated by Django 4.1.7 on 2023-04-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("url", models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tagname", models.CharField(max_length=128)),
                ("component_type", models.CharField(max_length=128)),
                ("style_string", models.JSONField(blank=True)),
                ("otherprops_string", models.JSONField(blank=True)),
                (
                    "children",
                    models.ManyToManyField(blank=True, to="landing_constructor.tag"),
                ),
            ],
        ),
    ]
