# Generated by Django 4.1.7 on 2023-04-02 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("landing_constructor", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="children",
        ),
        migrations.AddField(
            model_name="tag",
            name="children",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="landing_constructor.tag",
            ),
        ),
    ]
