# Generated by Django 4.1.7 on 2023-04-02 11:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("landing_constructor", "0002_remove_tag_children_tag_children"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tag",
            old_name="children",
            new_name="parent",
        ),
    ]
